from Sujet_01 import *
from Sujet_02 import *
from Sujet_03 import *
from Sujet_04 import *
from Sujet_05 import *
from Sujet_06 import *
from Sujet_07 import *
from Sujet_08 import *
from Sujet_09 import *
from Sujet_10 import *
from Sujet_11 import *
from Sujet_12 import *
from Sujet_13 import *
from Sujet_14 import *
from Sujet_15 import *
from Sujet_16 import *
from Sujet_17 import *
from Sujet_18 import *
from Sujet_19 import *
from Sujet_20 import *
from Sujet_21 import *
from Sujet_22 import *
from Sujet_23 import *
from Sujet_24 import *
from Sujet_25 import *
from Sujet_26 import *
from Sujet_27 import *
from Sujet_28 import *
from Sujet_29 import *
from Sujet_30 import *
from Sujet_31 import *
from Sujet_32 import *
from Sujet_33 import *
from Sujet_34 import *
from Sujet_35 import *
from Sujet_36 import *
from Sujet_37 import *
from Sujet_38 import *
from Sujet_39 import *
from Sujet_40 import *
from Sujet_41 import *
from Sujet_42 import *
from Sujet_43 import *
from Sujet_44 import *
from Sujet_45 import *